@StoreFront_HostAddress = http://localhost:5005

GET {{StoreFront_HostAddress}}/orders
Accept: application/json

### Send POST request with JSON body
# @name createOrder
POST {{StoreFront_HostAddress}}/orders
Content-Type: application/json

{
  "deliveryAddress": {
    "name": "John Doe",
    "number": "1234",
    "city": "London",
    "postalCode": "W12 0TZ"
  },
  "pizzas": [
    {
      "size": 2,
      "toppings": [
        {
          "topping": {
            "toppingId": 2
          }
        }
      ]
    }
  ]
}

###

GET {{StoreFront_HostAddress}}/orders/4/
Accept: application/json