// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'src\OpenTelemetry.SemanticConventions\scripts\templates\registry\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace Shared;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class PizzashopAttributes
{
    /// <summary>
    /// The id of the courier.
    /// </summary>
    /// <remarks>
    /// This is the unique id of the courier.
    /// </remarks>
    public const string PizzashopCourierId = "pizzashop.courier.id";

    /// <summary>
    /// The name of the courier.
    /// </summary>
    /// <remarks>
    /// This is the human readable name of the courier.
    /// </remarks>
    public const string PizzashopCourierName = "pizzashop.courier.name";

    /// <summary>
    /// The delivery address for an order.
    /// </summary>
    /// <remarks>
    /// This should be added wherever it's present.
    /// </remarks>
    public const string PizzashopOrderDeliveryAddress = "pizzashop.order.delivery_address";

    /// <summary>
    /// The orderid for a given order.
    /// </summary>
    /// <remarks>
    /// This should be added wherever it's present.
    /// </remarks>
    public const string PizzashopOrderId = "pizzashop.order.id";

    /// <summary>
    /// The number of pizzas in an order.
    /// </summary>
    /// <remarks>
    /// This should be added wherever it's present.
    /// </remarks>
    public const string PizzashopOrderPizzaCount = "pizzashop.order.pizza_count";

    /// <summary>
    /// The size of the pizza.
    /// </summary>
    /// <remarks>
    /// This should be added wherever it's present.
    /// </remarks>
    public const string PizzashopPizzaSize = "pizzashop.pizza.size";

    /// <summary>
    /// A list of the toppings.
    /// </summary>
    /// <remarks>
    /// This should be a comma separated list of toppings.
    /// </remarks>
    public const string PizzashopPizzaToppings = "pizzashop.pizza.toppings";
}